attacker_cls: "CrescendoAttacker"
attacker_name: "Crescendo"

attack_llm_config:
  llm_type: "OpenAiChatLLM"
  base_url: "https://aihubmix.com/v1"
  api_key: "sk-MI1czDjVIUVxVtzx519803081a574eB1BbE193196cF175D9"
  model_name: "DeepSeek-V3"
attack_llm_gen_config:
  max_n_tokens: 2048
  temperature: 0.0
  logprobs: False
  seed: 42

cache_dir: "../../data/Crescendo/harmbench_crescendo_cache_gpt-4o-2024-11-20.json"
max_turn: 10
