defender_cls: GradSafeDefender
defender_name: GradSafe

# target LLM
target_llm_config: 
  llm_type: HuggingFaceLLM
  model_name: meta-llama/Llama-3.2-3B-Instruct
  device_map: cuda:3 
target_llm_gen_config:
  max_n_tokens: 128
  temperature: 1.0
  logprobs: false
  seed: 42

# determine is safe or not
unsafe_threshold: 0.25

# default settings
# unsafe_set: 
# safe_set: 