attacker_cls: "IcaAttacker"
attacker_name: "ICA"

# target llm configs
target_llm_config:
#  llm_type: "HuggingFaceLLM"
#  model_name: "meta-llama/Llama-3.1-8B-Instruct"
#  device_map: cuda:0
  llm_type: "OpenAiChatLLM"
  base_url: "https://aihubmix.com/v1"
  api_key: "sk-2MW9jOjeoKGhlO78Bc8c1038B6924dB4B9A81881780048Aa"
  model_name: "llama3.1-8b"


target_llm_gen_config:
  max_n_tokens: 4096
  temperature: 1.0
  logprobs: False
  seed: null
