attacker:
  attacker_cls: "TransferAttacker"
  attacker_name: null

defender:
  defender_cls: "NoneDefender"
  target_llm_config:
    llm_type: "OpenAiLLM"
    model_name: "meta-llama/Meta-Llama-3-70B-Instruct"
    base_url: "http://172.18.129.80:8000/v1"
  target_llm_gen_config:
    max_n_tokens: 500
    temperature: 1.0
    logprobs: False
    seed: null

judges: null

misc:
  output_file: null
  threads: 1
  input_file: "../../data/sos_lite_expanded.csv"